config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('products/', include('products.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import HomeView, ContactView, ContactCreateView

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('contact/create/', ContactCreateView.as_view(), name='contact_create'),
]

products/urls.py
from django.urls import path


app_name = 'products'

urlpatterns = []

users/urls.py
from django.urls import path
from .views import login_view, registration_view, logout_view

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', registration_view, name='register'),

]

main/models.py
from django.db import models


class ContactMessageModel(models.Model):
    name = models.CharField(max_length=40)
    company_name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=15)
    lavozim = models.CharField(max_length=40)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'


class BannerModel(models.Model):
    collection = models.CharField(max_length=155)
    title = models.CharField(max_length=255)
    description = models.TextField()
    banner_image = models.ImageField(upload_to='banners/')
    banner_url = models.CharField(max_length=255)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'banner'
        verbose_name_plural = 'bannerlar'

products/models.py
from django.db import models


# class ProductColorModel(models.Model):
#     code = models.CharField(max_length=7)


class ProductTagModel(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Taglar'


# class ProductModel(models.Model):
#     title = models.CharField(max_length=50)
#     short_description = models.TextField()
#     long_description = models.TextField()
#     price = models.FloatField()
#     discount = models.PositiveIntegerField(default=0)
#     main_image = models.ImageField(upload_to='products/')
#     tag = models.ManyToManyRel(ProductTagModel, related_name='products')
#

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class UserModel(AbstractUser):
    pass

main/forms.py
from django import forms
from .models import ContactMessageModel


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessageModel
        exclude = ['created_at']
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': 'Ismingiz'
            }),
            'company_name': forms.TextInput(attrs={
                'placeholder': 'Firmangizni Nomi'
            }),
            'lavozim': forms.TextInput(attrs={
                'placeholder': 'Lavozimingiz',
                'value': 'Menedjer',
            }),
            'phone_number': forms.TextInput(attrs={
                'placeholder': 'Telefon Raqamingiz',
                'value': '+998 '
            }),

            'message': forms.TextInput(attrs={
                'placeholder': 'Sovolingiz'
            }),
        }

users/forms.py
from django import forms

from .models import UserModel
from django.core.exceptions import ValidationError


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'username'
    }), label=False)

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'password'
    }), label=False)


class RegistrationForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'username'
    }), label=False)

    email = forms.EmailField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'email'
    }), label=False)

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'password'
    }), label=False)

    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'confirm password'
    }), label=False)

    def clean_username(self):
        username = self.cleaned_data['username']
        user = UserModel.objects.get(username=username)
        if user:
            raise ValidationError(f'Ushbu {username} isimli username band')
        return self.cleaned_data['username']

    def clean_confirm_password(self):
        if self.cleaned_data['confirm_password'] != self.cleaned_data['password']:
            raise ValidationError('Parol birhil emas')
        return self.cleaned_data['confirm_password']

main/views.py
from django.shortcuts import render, reverse
from django.views.generic import TemplateView, CreateView
from .models import BannerModel
from .forms import ContactForm


class ContactView(TemplateView):
    template_name = 'contact.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['contact_form'] = ContactForm()
        return context


class ContactCreateView(CreateView):
    form_class = ContactForm

    def get_success_url(self):
        return reverse('main:contact')



class HomeView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['banners'] = BannerModel.objects.filter(status=True)
        return context

products/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render, redirect

from django.views.generic import TemplateView
from .forms import RegistrationForm, LoginForm
from .models import UserModel
from django.contrib.auth import login, logout, authenticate


def registration_view(request):
    form = RegistrationForm()

    if request.method == 'POST':
        form = RegistrationForm(data=request.POST)
        if form.is_valid():
            user = UserModel(username=form.cleaned_data['username'])
            user.set_password(form.cleaned_data['password'])
            user.save()
            return redirect('users:login')

    return render(request, 'login/register.html', context={
        'registration_form': form
    })


def login_view(request):
    form = LoginForm()

    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if not user is None:
                login(request, user)
    return render(request, 'login/index.html', context={
        'login_form': form
    })


def logout_view(request):
    logout(request)
    return redirect('users:login')

templates/chatPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/contact.html
{% extends 'layouts/base.html' %}
{% load static %}


{% block content %}
<!-- Map Begin -->
<div class="map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2995.038710680049!2d69.25795738631601!3d41.35151231549764!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38ae8d1406e2aaa9%3A0x7a67651caff6f05c!2sAlfa%20Karton%20Savdo!5e0!3m2!1sru!2s!4v1673159634820!5m2!1sru!2s"
            height="500" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
</div>
<!-- Map End -->

<!-- Contact Section Begin -->
<section class="contact spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6">
                <div class="contact__text">
                    <div class="section-title">
                        <span>Malumot</span>
                        <h2>Biz bilan boglaning</h2>
                        <p>As you might expect of a company that began as a high-end interiors contractor, we pay
                            strict attention.</p>
                    </div>
                    <ul>
                        <li>
                            <h4>Toshkent</h4>
                            <p>195 E Parker Square Dr, Parker, CO 801 <br/>+43 982-314-0958</p>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <div class="contact__form">
                    <form action="{% url 'main:contact_create' %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-6">
                                {{ contact_form.name }}
                            </div>
                            <div class="col-lg-6">
                                {{ contact_form.company_name }}
                            </div>
                            <div class="col-lg-6">
                                {{ contact_form.lavozim }}
                            </div>
                            <div class="col-lg-6">
                                {{ contact_form.phone_number }}
                            </div>
                            <div class="col-lg-12">
                                {{ contact_form.message }}
                                <button type="submit" class="site-btn">Send Message</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Contact Section End -->

{% endblock %}

templates/layouts/inc/navbar.html
{% load static %}

<!-- Offcanvas Menu Begin -->
<div class="offcanvas-menu-overlay"></div>
<div class="offcanvas-menu-wrapper">
    <div class="offcanvas__option">
        <div class="offcanvas__links">
            {% if not request.user.is_authenticated %}

                <a href="{% url 'users:login' %}">Sign in</a>
                <a href="{% url 'users:register' %}">Sign up</a>
            {% else %}
                <a href="{% url 'users:logout' %}">Logout</a>
            {% endif %}

        </div>
        <div class="offcanvas__top__hover">
            <span>Usd <i class="arrow_carrot-down"></i></span>
            <ul>
                <li>USD</li>
                <li>EUR</li>
                <li>USD</li>
            </ul>
        </div>
    </div>
    <div class="offcanvas__nav__option">
        <a href="#" class="search-switch"><img src="{% static 'main/img/icon/search.png' %}" alt=""></a>
        <a href="#"><img src="{% static 'main/img/icon/heart.png' %}" alt=""></a>
        <a href="#"><img src="{% static 'main/img/icon/cart.png' %}" alt=""> <span>0</span></a>
        <div class="price">$0.00</div>
    </div>
    <div id="mobile-menu-wrap"></div>
    <div class="offcanvas__text">
        <p></p>
    </div>
</div>
<!-- Offcanvas Menu End -->

<!-- Header Section Begin -->
<header class="header">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-7">
                    <div class="header__top__left">
                        <p></p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-5">
                    <div class="header__top__right">
                        <div class="header__top__links">
                            {% if not request.user.is_authenticated %}

                                <a href="{% url 'users:login' %}">Sign in</a>
                                <a href="{% url 'users:register' %}">Sign up</a>
                            {% else %}
                                <a href="{% url 'users:logout' %}">Logout</a>
                            {% endif %}
                        </div>
                        <div class="header__top__hover">
                            <span>Usd <i class="arrow_carrot-down"></i></span>
                            <ul>
                                <li>USD</li>
                                <li>EUR</li>
                                <li>USD</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="header__logo">
                    <a href="{% url 'main:home' %}"><img src="{% static 'main/img/logo.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <nav class="header__menu mobile-menu">
                    <ul>
                        <li class="active"><a href="{% url 'main:home' %}">Home</a></li>
                        <li><a href="">Shop</a></li>
                        <li><a href="#">Pages</a>
                            <ul class="dropdown">
                                <li><a href="./about.html">About Us</a></li>
                                <li><a href="./shop-details.html">Shop Details</a></li>
                                <li><a href="./shopping-cart.html">Shopping Cart</a></li>
                                <li><a href="./checkout.html">Check Out</a></li>
                                <li><a href="./blog-details.html">Blog Details</a></li>
                            </ul>
                        </li>
                        <li><a href="">Blog</a></li>
                        <li><a href="{% url 'main:contact' %}">Contacts</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="header__nav__option">
                    <a href="#" class="search-switch"><img src="{% static 'main/img/icon/search.png' %}" alt=""></a>
                    {% if request.user.is_authenticated %}
                        <a href="#"><img src="{% static 'main/img/icon/heart.png' %}" alt=""></a>
                        <a href="#"><img src="{% static 'main/img/icon/cart.png' %}" alt=""> <span>0</span></a>
                        <div class="price">$0.00</div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="canvas__open"><i class="fa fa-bars"></i></div>
    </div>
</header>
<!-- Header Section End -->

templates/login/index.html
{% extends 'layouts/login_base.html' %}
{% load static crispy_forms_tags %}


{% block content %}

    <div class="d-md-flex half">
        <div class="bg" style="background-image: url('{% static 'main/img/bg_1.jpg' %}');"></div>
        <div class="contents">

            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-md-12">
                        <div class="form-block mx-auto">
                            <div class="text-center mb-5">
                                <h3 class="text-uppercase">Login to <strong>male fashion</strong></h3>
                            </div>
                            <form action="{% url 'users:login' %}" method="post">
                                {% csrf_token %}
                                <div class="form-group first">
                                    <label for="username">Username</label>
                                    {{ login_form.username|as_crispy_field }}
                                </div>
                                <div class="form-group last mb-3">
                                    <label for="password">Password</label>
                                    {{ login_form.password|as_crispy_field }}
                                </div>

                                <div class="d-sm-flex mb-5 align-items-center">
                                    <span class="mb-3 mb-sm-0">
                                        <a href="{% url 'users:register' %}">Registration</a>
                                    </span>
                                    <span class="ml-auto"><a href="#" class="forgot-pass">Forgot Password</a></span>
                                </div>

                                <input type="submit" value="Log In" class="btn btn-block py-2 btn-primary">

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/login/register.html
{% extends 'layouts/login_base.html' %}
{% load static crispy_forms_tags %}


{% block content %}

    <div class="d-md-flex half">
        <div class="bg" style="background-image: url('{% static 'main/img/bg_1.jpg' %}');"></div>
        <div class="contents">

            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-md-12">
                        <div class="form-block mx-auto">
                            <div class="text-center mb-5">
                                <h3 class="text-uppercase">Registration to <strong>MALE_fashion</strong></h3>
                            </div>
                            <form action="{% url 'users:register' %}" method="post">
                                {% csrf_token %}
                                <div class="form-group first">
                                    <label for="username">Username <span style="color: red">*</span></label>
                                    {#                                    <input type="text" class="form-control" placeholder="username"#}
                                    {#                                           id="username">#}
                                    {{ registration_form.username|as_crispy_field }}
                                </div>

                                <div class="form-group first">
                                    <label for="username">Gmail <span style="color: red">*</span></label>
                                    {#                                    <input type="text" class="form-control" placeholder="your-email@gmail.com"#}
                                    {#                                           id="username">#}
                                    {{ registration_form.email|as_crispy_field }}
                                </div>
                                <div class="form-group last mb-3">
                                    <label for="password">Password <span style="color: red">*</span></label>
                                    {#                                    <input type="password" class="form-control" placeholder="Your Password"#}
                                    {#                                           id="password">#}
                                    {{ registration_form.password|as_crispy_field }}
                                </div>
                                {# password confirm #}
                                <div class="form-group last mb-3">
                                    <label for="password">ConfirmPassword <span style="color: red">*</span></label>
                                    {#                                    <input type="password" class="form-control" placeholder="Repeat Your Password"#}
                                    {#                                           id="password">#}
                                    {{ registration_form.confirm_password|as_crispy_field }}
                                </div>

                                <div class="d-sm-flex mb-5 align-items-center">
                                    <span class="mb-3 mb-sm-0">
                                        <a href="{% url 'users:login' %}">Login</a>
                                    </span>
                                </div>


                                <input  type="submit" value="Registration" class="btn btn-block py-2 btn-primary">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/order-history.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/shop.html
{% extends 'layouts/base.html' %}
{% load my_tags %}
{% load static %}


{% block content %}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Shop</h4>
                        <div class="breadcrumb__links">
                            <a href="{% url 'main:home' %}">Home</a>
                            <span>Shop</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shop Section Begin -->
    <section class="shop spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    {% include 'layouts/inc/shop_sidebar.html' %}
                </div>
                <div class="col-lg-9">
                    <div class="shop__product__option">
                        <div class="row">

                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="shop__product__option__left">
                                    <p>Showing {{ page_obj.start_index }}–{{ page_obj.end_index }}
                                        of {{ page_obj.paginator.count }} results</p>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="shop__product__option__right">
                                    {#                                    <p>Sort by Price:</p>#}
                                    <select onchange="addSearchParams('sort', this.value)">
                                        <option value="">Sort by Price:</option>
                                        <option {% if request.GET.sort == 'real_price' %}selected{% endif %}
                                                value="real_price">Low to High
                                        </option>
                                        <option {% if request.GET.sort == '-real_price' %}selected{% endif %}
                                                value="-real_price">High to Low
                                        </option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">

                        {% for object in object_list %}
                            <div class="col-lg-4 col-md-6 col-sm-6">
                                <div class="product__item sale">
                                    <div class="product__item__pic set-bg" data-setbg="{{ object.main_image.url }}">
                                        {% if object.is_discount %}
                                            <span class="label">Sale</span>
                                        {% endif %}

                                        {% if object.is_new %}
                                            <span style="color: #111111; width: 65.5px; height: 22.5px"
                                                  class="label bg-white {% if object.is_discount %}mt-4{% endif %}">New</span>
                                        {% endif %}


                                        <ul class="product__hover">
                                            {% if request.user.is_authenticated %}

                                                <li>
                                                    <a href=""><img src="{% static 'main/img/icon/heart.png' %}" alt=""></a>
                                                </li>

                                            {% else %}

                                                <li>
                                                    <a href="{% url 'users:login' %}"><img src="{% static 'main/img/icon/heart.png' %}" alt=""></a>
                                                </li>

                                            {% endif %}
                                            <li><a href="#"><img src="{% static 'main/img/icon/search.png' %}"
                                                                 alt=""></a></li>
                                        </ul>
                                    </div>
                                    <div class="product__item__text">
                                        <h6>{{ object.title }}</h6>
                                        <a href="#" class="add-cart">+ Add To Cart</a>
                                        <div class="rating">
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                        </div>

                                        <h5>${% if object.is_discount %}
                                            {{ object.real_price }}
                                            <del class="text-secondary">{{ object.price }}</del>
                                        {% else %}
                                            {{ object.price }}
                                        {% endif %}
                                        </h5>

                                        <div class="product__color__select">
                                            <label for="pc-4">
                                                <input type="radio" id="pc-4">
                                            </label>
                                            <label class="active black" for="pc-5">
                                                <input type="radio" id="pc-5">
                                            </label>
                                            <label class="grey" for="pc-6">
                                                <input type="radio" id="pc-6">
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                    {% if page_obj.paginate.count >= 1 %}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="product__pagination">

                                    {% for page in page_obj.paginator.page_range %}
                                        <a class="{% if page == page_obj.number %}active{% endif %}"
                                           href="?page={{ page }}">{{ page }}</a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
    <!-- Shop Section End -->

{% endblock %}

{% block extra_js %}
    <script>
        function addSearchParams(name, value) { // name = cat, brand. value = 1, 2, 3
            let searchParams = new URLSearchParams(window.location.search) // ?cat=1&brand

            if (searchParams.has(name) && searchParams.get(name) == value) { // 1 == 1
                searchParams.delete(name)
            } else {
                searchParams.set(name, value)
            }
            window.location.search = searchParams.toString()
        }

        $(".js-range-slider").ionRangeSlider({
            type: "double",
            grid: true,
            min: {{ min }},
            max: {{ max }},
            from: {% get_current_price request 0 %},
            to: {% get_current_price request 1 %},
            prefix: "$",
            onFinish(data) {
                addSearchParams('price', data.from.toString() + ';' + data.to.toString())
            }
        });


    </script>
{% endblock %}

templates/wishlist.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>

</body>
</html>